using log4net;
using MailKit;
using MailKit.Net.Smtp;
using MimeKit;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Clemakro.MailCheckClient
{
    public partial class AppMainForm : Form
    {
        private static readonly ILog logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public AppMainForm()
        {
            InitializeComponent();

            var appender = LogManager.GetRepository().GetAppenders().Where(a => a.Name == "RichTextBoxAppender").FirstOrDefault();
            if (appender != null)
            {
                ((RichTextBoxAppender)appender).RichTextBox = loggingRichTextBox;
            }
        }

        private void fileExitToolStripMenuItem_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void fileSettingsToolStripMenuItem_Click(object sender, EventArgs e)
        {
            logger.Debug("Open settings dialog...");
            using (AppSettingsForm appSettingsForm = new AppSettingsForm())
            {
                if (appSettingsForm.ShowDialog(this) == DialogResult.OK)
                {
                    Properties.Settings.Default.Save();
                    logger.Debug("Settings saved.");
                }
                else
                {
                    logger.Debug("Settings cancelled.");
                }
            }
        }

        private void AppMainForm_Load(object sender, EventArgs e)
        {
            logger.Info("Loaded, Version " + System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString());
        }

        private void fileRunToolStripMenuItem_Click(object sender, EventArgs e)
        {
            logger.Debug("Run...");

            if (fileRunToolStripMenuItem.Checked)
            {
                sendTimer.Stop();
                logger.Debug("Job state: Stopped.");
                fileRunToolStripMenuItem.Checked = false;
                fileSettingsToolStripMenuItem.Enabled = true;
                jobStateToolStripStatusLabel.Text = "Stopped";
            }
            else
            {
                fileSettingsToolStripMenuItem.Enabled = false;

                sendTimer.Interval = Decimal.ToInt32(Properties.Settings.Default.sendInterval) * 1000;
                sendTimer.Start();
                logger.Debug("Job state: Running.");
                fileRunToolStripMenuItem.Checked = true;
                jobStateToolStripStatusLabel.Text = "Running";

                sendTimer_Tick(null, null);
            }
        }

        private async void sendTimer_Tick(object sender, EventArgs e)
        {
            logger.Debug("Send Timer Tick");
            sendInfoToolStripStatusLabel.Text = "Sending...";

            Task sendTask = Task.Run(() =>
            {
                long ticks = DateTime.Now.Ticks;

                string hostName = Dns.GetHostName();
                string hostIPv4 = "unknown";
                IPAddress[] addresses = Dns.GetHostAddresses(hostName);
                foreach (IPAddress ip4 in addresses.Where(ip => ip.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork))
                {
                    hostIPv4 = ip4.ToString();
                    break;
                }

                MimeMessage message = new MimeMessage();
                message.From.Add(new MailboxAddress(Properties.Settings.Default.smtpFromName, Properties.Settings.Default.smtpFromAddress));
                message.To.Add(MailboxAddress.Parse(Properties.Settings.Default.smtpToAddress));
                message.Subject = String.Format("Mail Check Client {0}", ticks);

                message.Body = new TextPart("plain")
                {
                    Text = String.Format(
                        "Hello\n\nThis e-mail was automatically generated by Mail Check Client.\n\nVersion: {0}\nClient-Host: {1} ({2})\nClient-Timestamp: {3}\nTicks: {4}\n\nEnd of message.",
                        System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString(),
                        hostName, hostIPv4,
                        DateTime.Now,
                        ticks
                        )
                };

                

                using (SmtpClient client = Properties.Settings.Default.mailLoggingEnabled ? new SmtpClient(new ProtocolLogger(Properties.Settings.Default.mailLoggingFile)) : new SmtpClient())
                {
                    client.Timeout = Decimal.ToInt32(Properties.Settings.Default.smtpNetworkTimeout) * 1000;
                    client.ServerCertificateValidationCallback = NoSslCertificateValidationCallback;

                    try
                    {
                        if (Properties.Settings.Default.smtpSSL)
                        {
                            client.Connect(Properties.Settings.Default.smtpHost, Decimal.ToInt32(Properties.Settings.Default.smtpPort), MailKit.Security.SecureSocketOptions.Auto);
                        }
                        else
                        {
                            client.Connect(Properties.Settings.Default.smtpHost, Decimal.ToInt32(Properties.Settings.Default.smtpPort), false);
                        }

                        if (Properties.Settings.Default.smtpLoginUsername.Length > 0)
                        {
                            client.Authenticate(Properties.Settings.Default.smtpLoginUsername, Properties.Settings.Default.smtpLoginPassword);
                        }

                        logger.Info("Sending message...");
                        client.Send(message);
                        logger.Info("Message successfully sent.");
                    }
                    catch (Exception ex)
                    {
                        logger.Error("Sending mail failed", ex);
                    }
                    finally
                    {
                        client.Disconnect(true);
                    }
                }
            });

            await (sendTask);
            sendTask.Dispose();
            sendInfoToolStripStatusLabel.Text = "";
        }

        private static bool NoSslCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            return true;
        }
    }
}
